<!--Slider Area Start-->
<div class="slider-area">
    <div class="preview-2">
        <div id="nivoslider" class="slides">
            <a href="#"><img src="<?php echo $this->baseUrl('public/img/slider/slider-1.jpg');?>" alt="" title="#slider-1-caption1"/></a>
            <a href="#"><img src="<?php echo $this->baseUrl('public/img/slider/slider-2.jpg');?>" alt="" title="#slider-1-caption3"/></a>
        </div>
        <div id="slider-1-caption1" class="nivo-html-caption nivo-caption">
            <div class="timethai" style="
                position:absolute;
                bottom:0;
                left:0;
                background-color:rgba(224, 53, 80, 0.6);
                height:3px;
                -webkit-animation: myfirst 5000ms ease-in-out;
                -moz-animation: myfirst 5000ms ease-in-out;
                -ms-animation: myfirst 5000ms ease-in-out;
                animation: myfirst 5000ms ease-in-out;
        ">
            </div>
            <div class="banner-content slider-1 hidden-xs">
                <div class="text-content">
                    <h1 class="title1"><span>collections</span></h1>
                    <h2 class="title2" ><span>2015 new design</span></h2>																	<h3 class="title3">style Mozar always loved men in whatever fashion season spring  winter.</h3>																																					<div class="banner-readmore">
                        <a href="#" title="Read more">Read more</a>
                    </div>
                </div>
            </div>
        </div>

        <div id="slider-1-caption3" class="nivo-html-caption nivo-caption">
            <div class="timethai" style="
                position:absolute;
                bottom:0;
                left:0;
                background-color:rgba(224, 53, 80, 0.6);
                height:3px;
                -webkit-animation: myfirst 5000ms ease-in-out;
                -moz-animation: myfirst 5000ms ease-in-out;
                -ms-animation: myfirst 5000ms ease-in-out;
                animation: myfirst 5000ms ease-in-out;
        ">
            </div>
            <div class="banner-content slider-3 hidden-xs">
                <div class="text-content">
                    <h1 class="title1"><span>eyewear collection</span></h1>
                    <h2 class="title2" ><span>perfect  model 2015</span></h2>																<h3 class="title3">HOT summer fashion glasses accepted competitive price free shipping nationwide</h3>
                    <div class="banner-readmore">
                        <a href="#" title="Read more">Read more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Slider Area-->
<?php include("application/views/scripts/banner/banner-homepage.phtml"); ?>
<?php include("application/views/scripts/catalog/featured-product.phtml"); ?>
<?php include("application/views/scripts/catalog/new-product.phtml"); ?>
