<!--Service Area Start-->
<div class="service-area">
    <div class="container">
        <div class="service-padding">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-service">
                        <span class="fa fa-truck"></span>
                        <h3>fREE SHIPPING</h3>
                        <p>One order over $99</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-service">
                        <span class="fa fa-dropbox"></span>
                        <h3>Special gift cards</h3>
                        <p> Give the perfect gift</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-service">
                        <span class="fa fa-calendar-o"></span>
                        <h3>Daily promotion</h3>
                        <p> Set up perspiciatis unde</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 hidden-sm col-xs-12">
                    <div class="single-service">
                        <span class="fa fa-comments-o"></span>
                        <h3>Special gift cards</h3>
                        <p> Give the perfect gift</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Service Area-->
<!--Footer Widget Area Start-->
<div class="footer-widget-area">
    <div class="container">
        <div class="footer-widget-padding">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-widget">
                        <div class="footer-widget-title">
                            <h3>our support</h3>
                        </div>
                        <div class="footer-widget-list ">
                            <ul>
                                <li><a href="#">Sitemap</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Your Account</a></li>
                                <li><a href="#">Advanced Search</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 hidden-sm col-xs-12">
                    <div class="single-widget">
                        <div class="footer-widget-title">
                            <h3>My account</h3>
                        </div>
                        <div class="footer-widget-list ">
                            <ul>
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">Order History</a></li>
                                <li><a href="#">Returns</a></li>
                                <li><a href="#">Specials</a></li>
                                <li><a href="#">Site Map</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-widget">
                        <div class="footer-widget-title">
                            <h3>Contact us</h3>
                        </div>
                        <div class="footer-widget-list ">
                            <ul class="address">
                                <li><span class="fa fa-map-marker"></span> Addresss: Lorem ipsum dolor</li>
                                <li><span class="fa fa-phone"></span> (800) 0123 4567 890</li>
                                <li class="support-link"><span class="fa fa-envelope-o"></span> admin@bootexperts.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="single-widget">
                        <div class="footer-widget-title">
                            <h3>Sign up for newsletter</h3>
                        </div>
                        <div class="footer-widget-list ">
                            <form id="newsletter" method="post" action="#">
                                <div class="newsletter-content">
                                   <input type="text" name="email">
                                    <button class="button" type="submit"><span>Subscribe</span></button>
                                </div>
                            </form>
                            <ul class="social-link">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-rss"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Footer Widget Area-->
<!--Footer Area Start-->
<footer class="footer">
    <div class="container">
        <div class="footer-padding">
            <div class="row">
                <div class="col-lg-7 col-md-7 col-sm-8">
                    <nav>
                        <ul id="footer-menu">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Customer Service</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                        <p class="author">Copyright © 2016 <a href="#">BootExperts</a> All Rights Reserved.</p>
                    </nav>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-4">
                    <p class="payment-image">
                        <img src="<?php echo $this->baseUrl('public/img/payment.png');?>" alt="">
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--End of Footer Area-->
<!--Quickview Product Start -->
<div id="quickview-wrapper">
    <!-- Modal -->
    <div class="modal fade" id="productModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="modal-product">
                        <div class="product-images">
                            <div class="main-image images">
                                <img alt="" src="<?php echo $this->baseUrl('public/img/product/quick-view.jpg');?>">
                            </div>
                        </div>
                        <div class="product-info">
                            <h1>Diam quis cursus</h1>
                            <div class="price-box">
                                <p class="price"><span class="special-price"><span class="amount">$132.00</span></span></p>
                            </div>
                            <a href="product-details.html" class="see-all">See all features</a>
                            <div class="quick-add-to-cart">
                                <form method="post" class="cart">
                                    <div class="numbers-row">
                                        <input type="number" id="french-hens" value="3">
                                    </div>
                                    <button class="single_add_to_cart_button" type="submit">Add to cart</button>
                                </form>
                            </div>
                            <div class="quick-desc">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor. Donec non est at libero vulputate rutrum. Morbi ornare lectus quis justo gravida semper. Nulla tellus mi, vulputate adipiscing cursus eu, suscipit id nulla.
                            </div>
                            <div class="social-sharing">
                                <div class="widget widget_socialsharing_widget">
                                    <h3 class="widget-title-modal">Share this product</h3>
                                    <ul class="social-icons">
                                        <li><a target="_blank" title="Facebook" href="#" class="facebook social-icon"><i class="fa fa-facebook"></i></a></li>
                                        <li><a target="_blank" title="Twitter" href="#" class="twitter social-icon"><i class="fa fa-twitter"></i></a></li>
                                        <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="fa fa-pinterest"></i></a></li>
                                        <li><a target="_blank" title="Google +" href="#" class="gplus social-icon"><i class="fa fa-google-plus"></i></a></li>
                                        <li><a target="_blank" title="LinkedIn" href="#" class="linkedin social-icon"><i class="fa fa-linkedin"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .product-info -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End of Quickview Product-->
<!--Newsletter Popup Start-->
<div id="newsletter-popup-conatiner">
    <div id="newsletter-pop-up">
        <span class="hide-popup">Close</span>
        <div class="subscribe-pop-up">
            <div class="title-subscribe">
                <h1>NEWSLETTER</h1>
            </div>
            <form id="newsletter-form" method="post" action="#">
                <div class="content-subscribe">
                    <div class="form-subscribe-header">
                        <label>Subcribe to the Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat..</label>
                    </div>
                    <div class="input-box">
                       <input type="text" class="input-text newsletter-subscribe" title="Sign up for our newsletter" name="email">
                    </div>
                    <div class="actions">
                        <button class="button-subscribe" title="Subscribe" type="submit">Subscribe</button>
                    </div>
                </div>
            </form>
            <div class="subscribe-bottom">
                <input type="checkbox" id="dont_show">
                <label for="dont_show">Don't show this popup again</label>
            </div>
        </div>
    </div>
</div>
<!--End of Newsletter Popup-->

<!-- jquery
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/vendor/jquery-1.11.3.min.js');?>"></script>

<!-- bootstrap JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/bootstrap.min.js');?>"></script>

<!-- nivo slider js
============================================ -->
<script src="<?php echo $this->baseUrl('public/lib/nivo-slider/js/jquery.nivo.slider.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl('public/lib/nivo-slider/home.js');?>" type="text/javascript"></script>

<!-- wow JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/wow.min.js');?>"></script>

<!-- meanmenu JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/jquery.meanmenu.js');?>"></script>

<!-- owl.carousel JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/owl.carousel.min.js');?>"></script>

<!-- price-slider JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/jquery-price-slider.js');?>"></script>

<!-- scrollUp JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/jquery.scrollUp.min.js');?>"></script>

<!--Countdown js-->
<script src="<?php echo $this->baseUrl('public/js/jquery.countdown.min.js');?>"></script>

<!-- Sticky Menu JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/jquery.sticky.js');?>"></script>

<!-- Elevatezoom JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/jquery.elevateZoom-3.0.8.min.js');?>"></script>

<!-- plugins JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/plugins.js');?>"></script>

<!-- main JS
============================================ -->
<script src="<?php echo $this->baseUrl('public/js/main.js');?>"></script>
</body>
</html>
