<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>STICK-FRAME || lorem ipsum</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- favicon
		============================================ -->
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl('public/img/favicon.ico');?>">

		<!-- Google Fonts
		============================================ -->
        <link href='https://fonts.googleapis.com/css?family=Lato:400,400italic,900,700,700italic,300' rel='stylesheet' type='text/css'>

		<!-- Bootstrap CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/bootstrap.min.css');?>">

        <!-- nivo slider CSS
		============================================ -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl('public/lib/nivo-slider/css/nivo-slider.css');?>" type="text/css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('public/lib/nivo-slider/css/preview.css');?>" type="text/css" media="screen" />

		<!-- Fontawsome CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/font-awesome.min.css');?>">

		<!-- owl.carousel CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/owl.carousel.css');?>">

		<!-- jquery-ui CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/jquery-ui.css');?>">

		<!-- meanmenu CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/meanmenu.min.css');?>">

		<!-- animate CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/animate.css');?>">

		<!-- style CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/style.css');?>">

		<!-- responsive CSS
		============================================ -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/responsive.css');?>">

		<!-- modernizr JS
		============================================ -->
        <script src="<?php echo $this->baseUrl('public/js/vendor/modernizr-2.8.3.min.js');?>"></script>
    </head>
