<!-- Mobile Menu Area start -->
<div class="mobile-menu-area">
<div class="container">
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="mobile-menu">
          <nav id="dropdown">
              <ul>
                  <li><a href="index.html">HOME</a>
                      <ul>
                          <li><a href="index-2.html">Home 2</a></li>
                          <li><a href="index-3.html">Home 3</a></li>
                          <li><a href="index-4.html">Home 4</a></li>
                      </ul>
                  </li>
                  <li><a href="#">SHOP</a>
                      <ul>
                          <li><a href="shop-grid.html">Shop Grid</a></li>
                          <li><a href="shop-list.html">Shop List</a></li>
                          <li><a href="product-details.html">Product Details</a></li>
                      </ul>
                  </li>
                  <li><a href="blog.html">Blog</a>
                      <ul>
                          <li><a href="blog-details.html">Blog Details</a></li>
                      </ul>
                  </li>
                  <li><a href="about.html">ABOUT</a>
                  <li><a href="#">PAGES</a>
                      <ul>
                          <li><a href="account.html">My Account</a></li>
                          <li><a href="cart.html">Cart</a></li>
                          <li><a href="checkout.html">Checkout</a></li>
                          <li><a href="wishlist.html">Wishlist</a></li>
                      </ul>
                  </li>
                  <li><a href="contact.html">CONTACT</a></li>
              </ul>
          </nav>
      </div>
  </div>
</div>
</div>
</div>
<!-- Mobile Menu Area end -->
