<!--Mainmenu Start-->
<div class="mainmenu-area hidden-sm hidden-xs">
<div id="sticker">
<div class="container">
  <div class="row">
      <div class="col-lg-12 col-md-12 hidden-sm">
          <div class="mainmenu">
              <nav>
                  <ul id="nav">
                      <li class="current"><a href="index.html">Home</a>
                      </li>
                      <li><a href="shop-grid.html">Women</a>
                          <div class="megamenu">
                              <div class="megamenu-list clearfix">
                                  <span>
                                      <a href="#" class="mega-title">Clothing</a>
                                      <a href="#">Blazers</a>
                                      <a href="#">Jackets</a>
                                      <a href="#">Collections</a>
                                      <a href="#">T-Shirts</a>
                                  </span>
                                  <span>
                                      <a href="#" class="mega-title">Dresses</a>
                                      <a href="#">Cocktail</a>
                                      <a href="#">Sunglass</a>
                                      <a href="#">Evening</a>
                                      <a href="#">Footwear</a>
                                  </span>
                                  <span>
                                      <a href="#" class="mega-title">Handbags</a>
                                      <a href="#">Bootees Bags</a>
                                      <a href="#">Furniture</a>
                                      <a href="#">Exclusive</a>
                                      <a href="#">Jackets</a>
                                  </span>
                                  <span class="no-margin">
                                      <a href="#" class="mega-title">Jewellery</a>
                                      <a href="#">Earrings</a>
                                      <a href="#">Nosepins</a>
                                      <a href="#">Braclets</a>
                                      <a href="#">Bangels</a>
                                  </span>
                                  <span class="no-margin">
                                      <a href="#" class="mega-banner">
                                          <img src="<?php echo $this->baseUrl('public/img/mega-banner.jpg');?>" alt="">
                                      </a>
                                  </span>
                              </div>
                          </div>
                      </li>
                      <li><a href="shop-grid.html">Men</a>
                          <div class="megamenu">
                              <div class="megamenu-list clearfix">
                                  <span>
                                      <a href="#" class="mega-title">Clothing</a>
                                      <a href="#">Blazers</a>
                                      <a href="#">Jackets</a>
                                      <a href="#">Collections</a>
                                      <a href="#">T-Shirts</a>
                                  </span>
                                  <span>
                                      <a href="#" class="mega-title">Dresses</a>
                                      <a href="#">Cocktail</a>
                                      <a href="#">Sunglass</a>
                                      <a href="#">Evening</a>
                                      <a href="#">Footwear</a>
                                  </span>
                                  <span>
                                      <a href="#" class="mega-title">Handbags</a>
                                      <a href="#">Bootees Bags</a>
                                      <a href="#">Furniture</a>
                                      <a href="#">Exclusive</a>
                                      <a href="#">Jackets</a>
                                  </span>
                                  <span class="no-margin">
                                      <a href="#" class="mega-title">Jewellery</a>
                                      <a href="#">Earrings</a>
                                      <a href="#">Nosepins</a>
                                      <a href="#">Braclets</a>
                                      <a href="#">Bangels</a>
                                  </span>
                                  <span class="no-margin">
                                      <a href="#" class="mega-banner">
                                          <img src="<?php echo $this->baseUrl('public/img/mega-banner.jpg');?>" alt="">
                                      </a>
                                  </span>
                              </div>
                          </div>
                      </li>
                      <li><a href="shop-grid.html">Footwear</a></li>
                      <li><a href="index.html">Pages</a>
                          <ul class="sub-menu">
                              <li><a href="#" class="mega-title">Other Pages</a></li>
                              <li><a href="about.html">About Us</a></li>
                              <li><a href="blog.html">Blog Page</a></li>
                              <li><a href="blog-details.html">Blog Details Page</a></li>
                              <li><a href="account.html">My Account</a></li>
                              <li><a href="cart.html">Cart Page</a></li>
                              <li><a href="checkout.html">Checkout Page</a></li>
                              <li><a href="product-details.html">Product Details</a></li>
                              <li><a href="shop-grid.html">Shop Grid</a></li>
                              <li><a href="shop-list.html">Shop List</a></li>
                              <li><a href="wishlist.html">Wishlist</a></li>
                          </ul>
                      </li>
                      <li><a href="contact.html">Contact Us</a></li>
                  </ul>
              </nav>
          </div>
      </div>
  </div>
</div>
</div>
</div>
<!--End of Mainmenu-->
<?php include("application/views/scripts/include/menu-responsive.phtml"); ?>
