<!--Featured Product Carousel Area Start-->
<div class="featured-product-carousel-area">
<div class="container">
    <div class="section-padding">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title"><h2>FEATURED PRODUCTS</h2></div>
            </div>
        </div>
        <div class="row">
            <div class="product-carousel">
                <div class="col-md-3">
                    <!--item 1 start-->
                    <div class="single-product-item">
                        <div class="sale-product-label"><span>sale</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/21.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/9.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#"> Donec ac tempus </a></h2>
                        <div class="price-box">
                            <p class="old-price">
                                <span class="price">$899.00</span>
                            </p>
                            <p class="special-price">
                                <span class="price">$765.00</span>
                            </p>
                        </div>
                    </div><!--end of item 1-->
                </div><!--end of col-md-3-->
                <div class="col-md-3">
                    <!--item 2 start-->
                    <div class="single-product-item">
                        <div class="sale-product-label"><span>sale</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/15.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/14.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#">occaecati cupiditate</a></h2>
                        <div class="price-box">
                            <p class="old-price">
                                <span class="price">$170.00</span>
                            </p>
                            <p class="special-price">
                                <span class="price">$120.00</span>
                            </p>
                        </div>
                    </div><!--end of item 2-->
                </div><!--end of col-md-3-->
                <div class="col-md-3">
                    <!--item 3 start-->
                    <div class="single-product-item">
                        <div class="sale-product-label"><span>sale</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/13.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/12.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#">Primis in faucibus</a></h2>
                        <div class="price-box">
                            <p class="special-price">
                                <span class="price">$333.00</span>
                            </p>
                        </div>
                    </div><!--end of item 3-->
                </div><!--end of col-md-3-->
                <div class="col-md-3">
                    <!--item 4 start-->
                    <div class="single-product-item">
                        <div class="new-product-label"><span>new</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/2.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/3.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#">Etiam gravida</a></h2>
                        <div class="price-box">
                            <p class="old-price">
                                <span class="price">$222.00</span>
                            </p>
                        </div>
                    </div><!--end of item 4-->
                </div><!--end of col-md-3-->
                <div class="col-md-3">
                    <!--item 5 start-->
                    <div class="single-product-item">
                        <div class="new-product-label"><span>new</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/1.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/2.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#">Nunc facilisis </a></h2>
                        <div class="price-box">
                            <p class="special-price">
                                <span class="price">$423.00</span>
                            </p>
                        </div>
                   </div><!--end of item 5-->
                </div><!--end of col-md-3-->
                <div class="col-md-3">
                    <!--item 6 start-->
                    <div class="single-product-item">
                        <div class="sale-product-label"><span>sale</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/6.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/7.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#"> Tempus Donec le </a></h2>
                        <div class="price-box">
                            <p class="old-price">
                                <span class="price">$321.00</span>
                            </p>
                            <p class="special-price">
                                <span class="price">$222.00</span>
                            </p>
                        </div>
                   </div><!--end of item 6-->
                </div><!--end of col-md-3-->
                <div class="col-md-3">
                    <!--item 7 start-->
                    <div class="single-product-item">
                        <div class="new-product-label"><span>new</span></div>
                        <div class="single-product clearfix">
                            <a href="#">
                                <span class="product-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/8.jpg');?>" alt="">
                                </span>
                                <span class="product-image hover-image">
                                    <img src="<?php echo $this->baseUrl('public/img/product/9.jpg');?>" alt="">
                                </span>
                            </a>
                            <div class="button-actions clearfix">
                                <button class="button add-to-cart" type="button">
                                    <span><i class="fa fa-shopping-cart"></i></span>
                                </button>
                                <ul class="add-to-links">
                                    <li class="quickview">
                                        <a class="btn-quickview modal-view" href="#" data-toggle="modal" data-target="#productModal">
                                            <i class="fa fa-search-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a class="link-wishlist" href="wishlist.html">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    </li>																													<li>
                                        <a class="link-compare" href="#">
                                            <i class="fa fa-retweet"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h2 class="single-product-name"><a href="#">occaecati Primis</a></h2>
                        <div class="price-box">
                            <p class="special-price">
                                <span class="price">$453.00</span>
                            </p>
                        </div>
                   </div><!--end of item 7-->
                </div><!--end of col-md-3-->
            </div>
        </div>
    </div>
</div>
</div>
<!--End of Featured Product Carousel Area-->
